### ISSUE TITLE
Centralização de Token

### ISSUE THREAD

**Issue by MicahAbf** [douglaszporto/hubrpg-issues#10]
Percebi que criaturas com Token de tamanho 2x2, por exemplo, não centralizam entre os quadrados e sim no meio de um quadrado central.

- Como deveria ser centralizado:
![image](https://user-images.githubusercontent.com/65370107/161337760-1cd31dbd-a345-4504-b34b-beba4754a689.png)

- Como realmente é:
![image](https://user-images.githubusercontent.com/65370107/161338121-f7179d38-b06f-4f77-a517-422464d84387.png)

Sim... eu coloquei a imagem pra entender, pq nem eu entendi com a explicação.... Parece detalhe, mas pode causar muita confusão na cabeça de um usuário pouco experiente.

E sim, eu sei que o alinhamento é referente a uma célula e não ao conjunto de células... mas essa linha de pensamento é incompatível com o comportamento esperado do produto pelo cliente.

**Comment by douglaszporto** [comment]
Conforme conversado e explicado, há um ponto de ancoragem em cada token. Este ponto é SEMPRE o centro do token, forçando que tokens com dimenções pares (2x2. 4x4, etc) pareçam ficar desalinhados.

A solução, por hora, é ajustar manualmente a posição destes tokens.

Mas levantou-se a possibilidade de atribuir o tipo de alinhamento à cena, e não à operação do mestre, impedindo que tokens fiquem desalinhados entre colunas. Há outras problemáticas, tais como em cenas onde há tokens 1x1 e 2x2, misturados, portanto, a solução será melhor pensada e analizada.
