### ISSUE TITLE
Dimensão de Campo de Ficha

### ISSUE THREAD

**Issue by MicahAbf** [douglaszporto/hubrpg-issues#3]
Na "Criação de Ficha" ao editar um campo de "Número Decimal" não é possível selecionar 'Altura' menor que 2, o que leva a perda desnecessária de espaço na "Criação de Ficha".

![image](https://user-images.githubusercontent.com/65370107/158914914-3012489a-c3ed-4ecc-92ab-b4c6c093d692.png)

**Comment by douglaszporto** [comment]
Resolvido!

Entrará em funcionamento no próximo release (v20)
